# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import armazem_chave_valor_pb2 as armazem__chave__valor__pb2


class ArmazemChaveValorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insercao = channel.unary_unary(
                '/armazem.ArmazemChaveValor/Insercao',
                request_serializer=armazem__chave__valor__pb2.Chave_Valor.SerializeToString,
                response_deserializer=armazem__chave__valor__pb2.Inteiro.FromString,
                )
        self.Consulta = channel.unary_unary(
                '/armazem.ArmazemChaveValor/Consulta',
                request_serializer=armazem__chave__valor__pb2.Chave.SerializeToString,
                response_deserializer=armazem__chave__valor__pb2.Valor.FromString,
                )
        self.Ativacao = channel.unary_unary(
                '/armazem.ArmazemChaveValor/Ativacao',
                request_serializer=armazem__chave__valor__pb2.Valor.SerializeToString,
                response_deserializer=armazem__chave__valor__pb2.Inteiro.FromString,
                )
        self.Termino = channel.unary_unary(
                '/armazem.ArmazemChaveValor/Termino',
                request_serializer=armazem__chave__valor__pb2.Param_Vazio.SerializeToString,
                response_deserializer=armazem__chave__valor__pb2.Inteiro.FromString,
                )


class ArmazemChaveValorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insercao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consulta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ativacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Termino(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArmazemChaveValorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insercao': grpc.unary_unary_rpc_method_handler(
                    servicer.Insercao,
                    request_deserializer=armazem__chave__valor__pb2.Chave_Valor.FromString,
                    response_serializer=armazem__chave__valor__pb2.Inteiro.SerializeToString,
            ),
            'Consulta': grpc.unary_unary_rpc_method_handler(
                    servicer.Consulta,
                    request_deserializer=armazem__chave__valor__pb2.Chave.FromString,
                    response_serializer=armazem__chave__valor__pb2.Valor.SerializeToString,
            ),
            'Ativacao': grpc.unary_unary_rpc_method_handler(
                    servicer.Ativacao,
                    request_deserializer=armazem__chave__valor__pb2.Valor.FromString,
                    response_serializer=armazem__chave__valor__pb2.Inteiro.SerializeToString,
            ),
            'Termino': grpc.unary_unary_rpc_method_handler(
                    servicer.Termino,
                    request_deserializer=armazem__chave__valor__pb2.Param_Vazio.FromString,
                    response_serializer=armazem__chave__valor__pb2.Inteiro.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'armazem.ArmazemChaveValor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArmazemChaveValor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insercao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/armazem.ArmazemChaveValor/Insercao',
            armazem__chave__valor__pb2.Chave_Valor.SerializeToString,
            armazem__chave__valor__pb2.Inteiro.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Consulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/armazem.ArmazemChaveValor/Consulta',
            armazem__chave__valor__pb2.Chave.SerializeToString,
            armazem__chave__valor__pb2.Valor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ativacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/armazem.ArmazemChaveValor/Ativacao',
            armazem__chave__valor__pb2.Valor.SerializeToString,
            armazem__chave__valor__pb2.Inteiro.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Termino(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/armazem.ArmazemChaveValor/Termino',
            armazem__chave__valor__pb2.Param_Vazio.SerializeToString,
            armazem__chave__valor__pb2.Inteiro.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
