# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: armazem_chave_valor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='armazem_chave_valor.proto',
  package='armazem',
  syntax='proto3',
  serialized_options=b'\n\030io.grpc.examples.armazemB\021ArmazemChaveProtoP\001\242\002\003ARZ',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x61rmazem_chave_valor.proto\x12\x07\x61rmazem\"\x14\n\x07Inteiro\x12\t\n\x01v\x18\x01 \x01(\x05\"\x16\n\x05\x43have\x12\r\n\x05\x63have\x18\x01 \x01(\x04\"\x16\n\x05Valor\x12\r\n\x05valor\x18\x01 \x01(\t\"O\n\x0b\x43have_Valor\x12\x1f\n\x07\x63have_j\x18\x01 \x01(\x0b\x32\x0e.armazem.Chave\x12\x1f\n\x07valor_j\x18\x02 \x01(\x0b\x32\x0e.armazem.Valor\"\r\n\x0bParam_Vazio2\xdc\x01\n\x11\x41rmazemChaveValor\x12\x34\n\x08Insercao\x12\x14.armazem.Chave_Valor\x1a\x10.armazem.Inteiro\"\x00\x12,\n\x08\x43onsulta\x12\x0e.armazem.Chave\x1a\x0e.armazem.Valor\"\x00\x12.\n\x08\x41tivacao\x12\x0e.armazem.Valor\x1a\x10.armazem.Inteiro\"\x00\x12\x33\n\x07Termino\x12\x14.armazem.Param_Vazio\x1a\x10.armazem.Inteiro\"\x00\x42\x35\n\x18io.grpc.examples.armazemB\x11\x41rmazemChaveProtoP\x01\xa2\x02\x03\x41RZb\x06proto3'
)




_INTEIRO = _descriptor.Descriptor(
  name='Inteiro',
  full_name='armazem.Inteiro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='armazem.Inteiro.v', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=58,
)


_CHAVE = _descriptor.Descriptor(
  name='Chave',
  full_name='armazem.Chave',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='armazem.Chave.chave', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=82,
)


_VALOR = _descriptor.Descriptor(
  name='Valor',
  full_name='armazem.Valor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valor', full_name='armazem.Valor.valor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=106,
)


_CHAVE_VALOR = _descriptor.Descriptor(
  name='Chave_Valor',
  full_name='armazem.Chave_Valor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave_j', full_name='armazem.Chave_Valor.chave_j', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valor_j', full_name='armazem.Chave_Valor.valor_j', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=187,
)


_PARAM_VAZIO = _descriptor.Descriptor(
  name='Param_Vazio',
  full_name='armazem.Param_Vazio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=202,
)

_CHAVE_VALOR.fields_by_name['chave_j'].message_type = _CHAVE
_CHAVE_VALOR.fields_by_name['valor_j'].message_type = _VALOR
DESCRIPTOR.message_types_by_name['Inteiro'] = _INTEIRO
DESCRIPTOR.message_types_by_name['Chave'] = _CHAVE
DESCRIPTOR.message_types_by_name['Valor'] = _VALOR
DESCRIPTOR.message_types_by_name['Chave_Valor'] = _CHAVE_VALOR
DESCRIPTOR.message_types_by_name['Param_Vazio'] = _PARAM_VAZIO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Inteiro = _reflection.GeneratedProtocolMessageType('Inteiro', (_message.Message,), {
  'DESCRIPTOR' : _INTEIRO,
  '__module__' : 'armazem_chave_valor_pb2'
  # @@protoc_insertion_point(class_scope:armazem.Inteiro)
  })
_sym_db.RegisterMessage(Inteiro)

Chave = _reflection.GeneratedProtocolMessageType('Chave', (_message.Message,), {
  'DESCRIPTOR' : _CHAVE,
  '__module__' : 'armazem_chave_valor_pb2'
  # @@protoc_insertion_point(class_scope:armazem.Chave)
  })
_sym_db.RegisterMessage(Chave)

Valor = _reflection.GeneratedProtocolMessageType('Valor', (_message.Message,), {
  'DESCRIPTOR' : _VALOR,
  '__module__' : 'armazem_chave_valor_pb2'
  # @@protoc_insertion_point(class_scope:armazem.Valor)
  })
_sym_db.RegisterMessage(Valor)

Chave_Valor = _reflection.GeneratedProtocolMessageType('Chave_Valor', (_message.Message,), {
  'DESCRIPTOR' : _CHAVE_VALOR,
  '__module__' : 'armazem_chave_valor_pb2'
  # @@protoc_insertion_point(class_scope:armazem.Chave_Valor)
  })
_sym_db.RegisterMessage(Chave_Valor)

Param_Vazio = _reflection.GeneratedProtocolMessageType('Param_Vazio', (_message.Message,), {
  'DESCRIPTOR' : _PARAM_VAZIO,
  '__module__' : 'armazem_chave_valor_pb2'
  # @@protoc_insertion_point(class_scope:armazem.Param_Vazio)
  })
_sym_db.RegisterMessage(Param_Vazio)


DESCRIPTOR._options = None

_ARMAZEMCHAVEVALOR = _descriptor.ServiceDescriptor(
  name='ArmazemChaveValor',
  full_name='armazem.ArmazemChaveValor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=205,
  serialized_end=425,
  methods=[
  _descriptor.MethodDescriptor(
    name='Insercao',
    full_name='armazem.ArmazemChaveValor.Insercao',
    index=0,
    containing_service=None,
    input_type=_CHAVE_VALOR,
    output_type=_INTEIRO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Consulta',
    full_name='armazem.ArmazemChaveValor.Consulta',
    index=1,
    containing_service=None,
    input_type=_CHAVE,
    output_type=_VALOR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Ativacao',
    full_name='armazem.ArmazemChaveValor.Ativacao',
    index=2,
    containing_service=None,
    input_type=_VALOR,
    output_type=_INTEIRO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Termino',
    full_name='armazem.ArmazemChaveValor.Termino',
    index=3,
    containing_service=None,
    input_type=_PARAM_VAZIO,
    output_type=_INTEIRO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARMAZEMCHAVEVALOR)

DESCRIPTOR.services_by_name['ArmazemChaveValor'] = _ARMAZEMCHAVEVALOR

# @@protoc_insertion_point(module_scope)
