# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servidor_central.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servidor_central.proto',
  package='servidor',
  syntax='proto3',
  serialized_options=b'\n\030io.grpc.examples.centralB\014CentralProtoP\001\242\002\003SVC',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16servidor_central.proto\x12\x08servidor\"\x1f\n\rIdentificador\x12\x0e\n\x06str_id\x18\x01 \x01(\t\"\x16\n\x05\x43have\x12\r\n\x05\x63have\x18\x01 \x01(\x04\"\x1d\n\x0cLista_Chaves\x12\r\n\x05\x63have\x18\x01 \x03(\x04\"S\n\x08Id_Chave\x12#\n\x02id\x18\x01 \x01(\x0b\x32\x17.servidor.Identificador\x12\"\n\x02\x63h\x18\x02 \x01(\x0b\x32\x16.servidor.Lista_Chaves\"\x14\n\x07Inteiro\x12\t\n\x01v\x18\x01 \x01(\x05\"\r\n\x0bParam_Vazio2\xb7\x01\n\x0fServidorCentral\x12\x33\n\x08Registro\x12\x12.servidor.Id_Chave\x1a\x11.servidor.Inteiro\"\x00\x12\x38\n\nMapeamento\x12\x0f.servidor.Chave\x1a\x17.servidor.Identificador\"\x00\x12\x35\n\x07Termino\x12\x15.servidor.Param_Vazio\x1a\x11.servidor.Inteiro\"\x00\x42\x30\n\x18io.grpc.examples.centralB\x0c\x43\x65ntralProtoP\x01\xa2\x02\x03SVCb\x06proto3'
)




_IDENTIFICADOR = _descriptor.Descriptor(
  name='Identificador',
  full_name='servidor.Identificador',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='str_id', full_name='servidor.Identificador.str_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=67,
)


_CHAVE = _descriptor.Descriptor(
  name='Chave',
  full_name='servidor.Chave',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='servidor.Chave.chave', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=91,
)


_LISTA_CHAVES = _descriptor.Descriptor(
  name='Lista_Chaves',
  full_name='servidor.Lista_Chaves',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='servidor.Lista_Chaves.chave', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=122,
)


_ID_CHAVE = _descriptor.Descriptor(
  name='Id_Chave',
  full_name='servidor.Id_Chave',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='servidor.Id_Chave.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ch', full_name='servidor.Id_Chave.ch', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=207,
)


_INTEIRO = _descriptor.Descriptor(
  name='Inteiro',
  full_name='servidor.Inteiro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='servidor.Inteiro.v', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=229,
)


_PARAM_VAZIO = _descriptor.Descriptor(
  name='Param_Vazio',
  full_name='servidor.Param_Vazio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=244,
)

_ID_CHAVE.fields_by_name['id'].message_type = _IDENTIFICADOR
_ID_CHAVE.fields_by_name['ch'].message_type = _LISTA_CHAVES
DESCRIPTOR.message_types_by_name['Identificador'] = _IDENTIFICADOR
DESCRIPTOR.message_types_by_name['Chave'] = _CHAVE
DESCRIPTOR.message_types_by_name['Lista_Chaves'] = _LISTA_CHAVES
DESCRIPTOR.message_types_by_name['Id_Chave'] = _ID_CHAVE
DESCRIPTOR.message_types_by_name['Inteiro'] = _INTEIRO
DESCRIPTOR.message_types_by_name['Param_Vazio'] = _PARAM_VAZIO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Identificador = _reflection.GeneratedProtocolMessageType('Identificador', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFICADOR,
  '__module__' : 'servidor_central_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Identificador)
  })
_sym_db.RegisterMessage(Identificador)

Chave = _reflection.GeneratedProtocolMessageType('Chave', (_message.Message,), {
  'DESCRIPTOR' : _CHAVE,
  '__module__' : 'servidor_central_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Chave)
  })
_sym_db.RegisterMessage(Chave)

Lista_Chaves = _reflection.GeneratedProtocolMessageType('Lista_Chaves', (_message.Message,), {
  'DESCRIPTOR' : _LISTA_CHAVES,
  '__module__' : 'servidor_central_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Lista_Chaves)
  })
_sym_db.RegisterMessage(Lista_Chaves)

Id_Chave = _reflection.GeneratedProtocolMessageType('Id_Chave', (_message.Message,), {
  'DESCRIPTOR' : _ID_CHAVE,
  '__module__' : 'servidor_central_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Id_Chave)
  })
_sym_db.RegisterMessage(Id_Chave)

Inteiro = _reflection.GeneratedProtocolMessageType('Inteiro', (_message.Message,), {
  'DESCRIPTOR' : _INTEIRO,
  '__module__' : 'servidor_central_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Inteiro)
  })
_sym_db.RegisterMessage(Inteiro)

Param_Vazio = _reflection.GeneratedProtocolMessageType('Param_Vazio', (_message.Message,), {
  'DESCRIPTOR' : _PARAM_VAZIO,
  '__module__' : 'servidor_central_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Param_Vazio)
  })
_sym_db.RegisterMessage(Param_Vazio)


DESCRIPTOR._options = None

_SERVIDORCENTRAL = _descriptor.ServiceDescriptor(
  name='ServidorCentral',
  full_name='servidor.ServidorCentral',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=247,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='Registro',
    full_name='servidor.ServidorCentral.Registro',
    index=0,
    containing_service=None,
    input_type=_ID_CHAVE,
    output_type=_INTEIRO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Mapeamento',
    full_name='servidor.ServidorCentral.Mapeamento',
    index=1,
    containing_service=None,
    input_type=_CHAVE,
    output_type=_IDENTIFICADOR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Termino',
    full_name='servidor.ServidorCentral.Termino',
    index=2,
    containing_service=None,
    input_type=_PARAM_VAZIO,
    output_type=_INTEIRO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVIDORCENTRAL)

DESCRIPTOR.services_by_name['ServidorCentral'] = _SERVIDORCENTRAL

# @@protoc_insertion_point(module_scope)
